### ISSUE TITLE
Conflicting definition of IndexType

### ISSUE THREAD

**Issue by nselliott** [LLNL/axom#43] opened 2019-05-20 23:12 UTC
In src/axom/core/Types.hpp we have:

```
 #if defined(AXOM_USE_64BIT_INDEXTYPE) && !defined(AXOM_NO_INT64_T)
 using IndexType = int64;
 #else
 using IndexType = int32;
 #endif
```

And in src/axom/sidre/core/SidreTypes.hpp we have:

```
 typedef SIDRE_IndexType IndexType;
```

SIDRE_IndexType is elsewhere defined as int64_t.  We should define IndexType in only one place.

**Comment by gzagaris** [comment] 2019-05-20 23:21
I think this could be probably fixed by adding the ``cpp_if`` in the ``sidre_shroud.yaml`` (hopefully) or we need to do something like that. We are using that in quest for conditionally compiling routines that take an MPI communicator, but, I am not sure if we can use it out-of-the-box for types.

@ltaylor16 thoughts?

**Comment by kennyweiss** [comment] 2019-05-20 23:42
Thanks @nselliott.

The problem is actually here: 
https://github.com/LLNL/axom/blob/7c1185420de47bbd4ccf466b9c5f1e38fd69891d/src/axom/sidre/core/SidreDataTypeIds.h#L23-L25

If we still need `SIDRE_IndexType`, I think it should be defined as follows:
```cpp
using SIDRE_IndexType = axom::IndexType;
```

Since `axom::IndexType` defaults to 32 bits, and this one redefines it to 64 bits, this definitely needs to be resolved.

**Comment by kennyweiss** [comment] 2019-05-20 23:48
Here are the relevant lines in Sidre's shroud:
https://github.com/LLNL/axom/blob/7c1185420de47bbd4ccf466b9c5f1e38fd69891d/src/axom/sidre/interface/sidre_shroud.yaml#L30-L35

@ltaylor16 -- could this line be changed to support a configuration dependent type (e.g. `int32_t` or `int64_t`) based on `AXOM_USE_64BIT_INDEXTYPE`?

**Comment by gzagaris** [comment] 2019-05-21 02:18
Hmm....I am surprised we are hardcoding `SIDRE_IndexType` ourselves. I thought that shroud ``shroud`` would emit its definition. I understand this was done a while ago, but, is there a reason ``shroud`` couldn't do this?

For example, based on how we do something similar in ``quest`` could we do something like this:
```
declarations:
   -decl: #define SIDRE_IndexType int64_t
     fields:
          c_header: axom/sidre/interface/SidreTypes.hpp
          cpp_if: ifdef AXOM_USE_64BIT_INDEXTYPE
   -decl: #define SIDRE_IndexType int32_t
     fields:
          c_header: axom/sidre/interface/SidreTypes.hpp
          cpp_if: ifndef AXOM_USE_64BIT_INDEXTYPE

```

**Comment by kennyweiss** [comment] 2019-12-27 03:41
This issue appears to still be outstanding.

@ltaylor16 -- it seems like this is only necessary for Sidre's Fortran interface.
Can ``shroud`` handle a configurable ``SIDRE_IndexType`` to allow us to set ``SIDRE_IndexType`` to ``core::IndexType``, which can either be an ``int32`` or int64``?

**Comment by rhornung67** [comment] 2021-10-12 21:54
See: https://github.com/LLNL/axom/issues/194

**Comment by rhornung67** [comment] 2022-01-10 21:22
We also have declarations like this sprinkled around in C++ code: https://github.com/LLNL/axom/blob/develop/src/axom/sidre/core/Buffer.hpp#L123
the we do this in the associated shroud layer: https://github.com/LLNL/axom/blob/develop/src/axom/sidre/interface/sidre_shroud.yaml#L473

I think we can make the C++ usage consistent without having a Sidre-specific index type (i.e., use a centrally-defined index type in Axom core), but I'm not sure what we can do to support Fortran via shroud (as has been discussed in this conversation previously).

@ltaylor16 What is the semantic meaning of the definition of IndexType vs. SIDRE_IndexType here? https://github.com/LLNL/axom/blob/develop/src/axom/sidre/interface/sidre_shroud.yaml#L36  Our API annotated in the yaml file contains 'IndexType' everywhere. Then this gets replaced by 'SIDRE_IndexType' in the generated C and Fortran interface files. Is it possible to have Shroud generate an interface for int32_t and another for int64_t and have each guarded so the right one gets used based on the compile time specified value of AXOM_USE_64BIT_INDEXTYPE? I believe this is what @kennyweiss @gzagaris were asking about earlier.

**Comment by ltaylor16** [comment] 2022-01-24 18:03
The Fortran module should create a parameter of the integer type using a splicer. ``C_INT32_T`` and ``C_INT64_T`` are both part of the intrinsic module ``iso_c_bindings``.

      #if defined(AXOM_USE_64BIT_INDEXTYPE)
      integer, parameter :: INDEXTYPE = C_INT64_T
      #else
      integer, parameter :: INDEXTYPE = C_INT32_T
      #endif

The C wrapper will also need a splicer

      #if defined(AXOM_USE_64BIT_INDEXTYPE)
      typedef int64_t IndexType;
      #else
      typedef int32_t IndexType;
      #endif

Then allow a typemap in the YAML file which defines how C++ IndexType should be expanded so that the C++ argument

    IndexType arg

becomes

    integer(INDEXTYPE) arg

Creating a custom typemap for an integer type in the YAML file requires some changes to ``shroud``.

**Comment by ltaylor16** [comment] 2022-01-24 18:05
Eventually, there should be a Fortran wrapper for the core package since ``IndexType`` is defined there.  Defining it in ``sidre`` will work for now until another Fortran wrapped package requires ``IndexType``.

**Comment by ltaylor16** [comment] 2022-06-01 03:17
I manually changed ``sidre::IndexType`` to be ``int64_t`` and ran into some compile problems in the Fortran and runtime problems with C++.

    ...src/axom/sidre/interface/c_fortran/wrapfsidre.F:377:27:
             generic :: apply => apply_0, apply_nelems, apply_nelems_offset,  &
                                   1
    Error: 'view_apply_nelems_offset_stride' and 'view_apply_type_nelems_offset' for GENERIC 'apply' at (1) are ambiguous
    make[2]: *** [axom/sidre/CMakeFiles/sidre.dir/interface/c_fortran/wrapfsidre.F.o] Error 1

These two functions are generic for apply, think of it as C++ overloaded.  It can not tell them apart when ``INDEXTYPE`` is the same as ``C_INT``

    subroutine view_apply_nelems_offset_stride(obj, num_elems, offset, &
            stride)
        class(SidreView) :: obj
        integer(INDEXTYPE), value, intent(IN) :: num_elems
        integer(INDEXTYPE), value, intent(IN) :: offset
        integer(INDEXTYPE), value, intent(IN) :: stride

    subroutine view_apply_type_nelems_offset(obj, type, num_elems, &
            offset)
        use iso_c_binding, only : C_INT
        class(SidreView) :: obj
        integer(C_INT), value, intent(IN) :: type
        integer(INDEXTYPE), value, intent(IN) :: num_elems
        integer(INDEXTYPE), value, intent(IN) :: offset

The first function is defined by this declaration.  Shroud creates a function for each variant then overloads them. So it makes functions for ``(num_elems)``, ``(num_elems, offset)``, and ``(num_elems, offset, stride)``.

      - decl: View* apply(IndexType num_elems,
                          IndexType offset = 0,
                          IndexType stride = 1)

      - decl: View* apply(TypeID type,
                          IndexType num_elems,
                          IndexType offset = 0,
                         IndexType stride = 1)

I commented out some code and got it to compile.  The ``sidre_external_test`` fails because it calls the wrong overload when ``IndexType`` is ``int32``.  It called the first function when it should of called the second.


    View* Group::createView(const std::string& path,
                            TypeID type,
                            int ndims,
                            const IndexType* shape)


    View* Group::createView(const std::string& path,
                            TypeID type,
                            IndexType num_elems,
                            void* external_ptr)

Is there some clever C++ syntax to tell it to avoid the type promotion or whatever it's doing?

**Comment by ltaylor16** [comment] 2022-06-01 03:26
The fundamental problem is that we need the type defined consistently in three languages:
C++

    using SIDRE_IndexType = axom::IndexType;

C

    typedef int64_t SIDRE_IndexType

Fortran

    integer, parameter :: indextype = C_INT64_T

C and Fortran have no direct way to find the size of ``axom::IndexType``.  One option is to generate files at config time based on the ``AXOM_USE_64BIN_INDEXTYPE``

**Comment by ltaylor16** [comment] 2022-06-01 15:34
I think it would be simpler to just use the preprocessor and duplicate the test that is in ``core/Types.hpp`` in the C and Fortran wrappers using the language appropriate setting of IndexType.

    #if defined(AXOM_USE_64BIT_INDEXTYPE) && !defined(AXOM_NO_INT64_T)
    using IndexType = int64;
    #else
    using IndexType = int32;
    #endif

**Comment by rhornung67** [comment] 2022-06-01 16:00
I agree. We may need to have multiple type definitions along the path to making everything consistent. In the end, I think we should converge to having one index type defined at compile time, preferably defined in Axom core and other Axom parts use that. Is there any reason we would need to have the sidre index type be different?

**Comment by ltaylor16** [comment] 2022-06-09 23:19
At the AXOM meeting Monday we decided to rename the overloaded functions which were resolved incorrectly with `Indextype` as `int32`. The new name would be `createViewWithShape`.
@rhornung67 mentioned the option of using a different type to help resolve the overload.  I add `using Shape = std::vector<Indextype>` and replaced arguments `int ndims, IndexType *shape` with `Shape &shape`.  That compiled with `IndexType` as `int32` and `int64` and passed tests.  I had the Fortran interface turned off for this test.
I'm happy with this since it avoids a new function name. Are there any issues with having a `std::vector` in the API? The shape is stored in the `View` as a vector.
However, I think it still needs a Shroud update before the Fortran interface would work.

**Comment by rhornung67** [comment] 2022-06-09 23:28
My preference would be to rename the methods "...WithShape" to make it more clear. But, I have no issues with what @ltaylor16 is proposing.

**Closed** 2022-06-28 17:24 UTC
Labels: bug, Sidre, Reviewed

**Comment by rhornung67** [comment] 2022-06-28 17:26
Good to see issue #43 resolved now that we are in the 800s for issue numbers 😄

**Comment by nselliott** [comment] 2022-06-28 17:42
I wish I remembered what I was trying to do when I discovered this.
