### ISSUE TITLE
Inconsistent sidre::IndexType and axom::IndexType

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#194] opened 2020-03-27 03:11 UTC
We define `axom::IndexType` in axom core as follows:
https://github.com/LLNL/axom/blob/1827916b4741f3d7402397a4bfd98d132cd3b656/src/axom/core/Types.hpp#L49-L53

Sidre defines `sidre::IndexType` as `SIDRE_IndexType`:
https://github.com/LLNL/axom/blob/1827916b4741f3d7402397a4bfd98d132cd3b656/src/axom/sidre/core/SidreTypes.hpp#L43-L47

`SIDRE_IndexType` is in turn defined as:
https://github.com/LLNL/axom/blob/1827916b4741f3d7402397a4bfd98d132cd3b656/src/axom/sidre/core/SidreDataTypeIds.h#L23

Could we use `axom::IndexType` consistently in `Sidre` instead of having yet another `sidre::IndexType` defined? It seems confusing to have both...

Alternatively, could we employ the same conditional logic compile-time logic, so at least `sidre::IndexType` and `axom::IndexType` are consistent and can be used interchangeably? Is there a strong reason that `sidre::IndexType` must alway be `int64_t`? e.g., due to the way we do our Fortran wrappers etc.?

**Comment by rhornung67** [comment] 2021-10-12 21:54
See: https://github.com/LLNL/axom/issues/43

**Comment by ltaylor16** [comment] 2022-06-01 00:47
Duplicate of #43

**Closed by ltaylor16** 2022-06-01 00:47 UTC
Labels: Sidre, Reviewed
