### ISSUE TITLE
Octree failure for C2C contour.

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/axom#980] opened 2022-12-12 19:33 UTC
I was making a new C2C dataset and noticed that about a third of my C2C contours caused the Octree in Axom to crash. Many of these contours contain spline edges.

black65.contour
```
piece = line(start=(32cm,128cm), end=(38cm,147cm))
piece = line(end=(44cm,146cm))
piece = rz(units=cm,
  rz=44 146
     43 142
     36 125
     33 119
     30 117
     27 121
)

piece = line(end=(32cm,128cm))
```

black65.yaml
```
dimensions: 2
shapes:
- name: black65
  material: black
  geometry:
    format: c2c
    path: black65.contour
```

Klee command lines (note paths are different here for real files):
```
rzgenie7{whitlocb}36: data_collection_util --min 100 25 --max 150 50 --res 150 200 -p 1
[INFO]: Creating a box mesh of resolution (150,200) and bounding box { min:(100,25); max:(150,50); range:<50,25> }
[INFO]: After transformations, mesh has 30000 elements and (approximate) bounding box { min:(100,25); max:(150,50); range:<50,25> }
[INFO]: Saving mesh file 'box_2d'
rzgenie7{whitlocb}37: ../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp
[INFO]: After loading mesh has 30000 elements and (approximate) bounding box { min:(100,25); max:(150,50); range:<50,25> }
[INFO]: ========================Sampling InOut fields for shapes========================
[INFO]: --------------------------- Loading shape 'black65' ----------------------------
[INFO]: Reading file: ../../data/shaping/../contours/heroic_roses/black65.contour...
[INFO]: Loading contour with 4 pieces
[INFO]: ---------------------------- Generating the octree -----------------------------
[INFO]: Mesh bounding box: { min:(117.004,27); max:(173.182,52.2397); range:<56.1773,25.2397> }
[INFO]:   Generating InOutOctree over surface mesh with 208 vertices and 200 elements.
[INFO]: 	--Inserting vertices took 0.001122898 seconds.
[INFO]: 	--Updating mesh took 0.00115438 seconds.
[INFO]:   After inserting vertices, reindexed mesh has 200 vertices and 200 cells.
[DEBUG]: Inside InOutOctree::checkValid() to verify state of PR octree
[DEBUG]: --Checking that each vertex is in a leaf block of the tree.
[DEBUG]: done.
[DEBUG]: 	Inserting cells into level 0 took 0.000848126 seconds.
[DEBUG]: 	Inserting cells into level 1 took 0.000841897 seconds.
[DEBUG]: 	Inserting cells into level 2 took 0.000814332 seconds.
[DEBUG]: 	Inserting cells into level 3 took 0.000979541 seconds.
[DEBUG]: 	Inserting cells into level 4 took 0.0011968 seconds.
[DEBUG]: 	Inserting cells into level 5 took 0.00116284 seconds.
[DEBUG]: 	Inserting cells into level 6 took 0.00102629 seconds.
[DEBUG]: 	Inserting cells into level 7 took 0.000425237 seconds.
[DEBUG]: 	Inserting cells into level 8 took 0.000124968 seconds.
[DEBUG]: 	Inserting cells into level 9 took 7.7409e-05 seconds.
[DEBUG]: 	Inserting cells into level 10 took 4.3584e-05 seconds.
[DEBUG]: 	Inserting cells into level 11 took 5.0667e-05 seconds.
[DEBUG]: 	Inserting cells into level 12 took 5.459e-05 seconds.
[DEBUG]: 	Inserting cells into level 13 took 5.3638e-05 seconds.
[DEBUG]: 	Inserting cells into level 14 took 5.3061e-05 seconds.
[DEBUG]: 	Inserting cells into level 15 took 5.2852e-05 seconds.
[DEBUG]: 	Inserting cells into level 16 took 4.5964e-05 seconds.
[DEBUG]: 	Inserting cells into level 17 took 5.5759e-05 seconds.
[DEBUG]: 	Inserting cells into level 18 took 5.5097e-05 seconds.
[DEBUG]: 	Inserting cells into level 19 took 5.2937e-05 seconds.
[DEBUG]: 	Inserting cells into level 20 took 5.2406e-05 seconds.
[DEBUG]: 	Inserting cells into level 21 took 5.2285e-05 seconds.
[DEBUG]: 	Inserting cells into level 22 took 5.3281e-05 seconds.
[DEBUG]: 	Inserting cells into level 23 took 5.4209e-05 seconds.
[DEBUG]: 	Inserting cells into level 24 took 5.271e-05 seconds.
[DEBUG]: 	Inserting cells into level 25 took 5.3548e-05 seconds.
[DEBUG]: 	Inserting cells into level 26 took 5.3548e-05 seconds.
[DEBUG]: 	Inserting cells into level 27 took 5.3823e-05 seconds.
[DEBUG]: 	Inserting cells into level 28 took 5.3194e-05 seconds.
[DEBUG]: 	Inserting cells into level 29 took 5.3634e-05 seconds.
[ERROR]: Failed Assert: idx >= 0 && idx < SetPosition(m_data.size())
Attempted to access element 31 but map's data has size 31
** StackTrace of 12 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: axom::slam::Map<axom::spin::OctreeLevel<2, axom::quest::InOutBlockData>*, axom::slam::Set<int, int>, axom::slam::policies::STLVectorIndirection<int, axom::spin::OctreeLevel<2, axom::quest::InOutBlockData>*>, axom::slam::policies::StrideOne<int> >::verifyPositionImpl(int) const
Frame 3: axom::slam::Map<axom::spin::OctreeLevel<2, axom::quest::InOutBlockData>*, axom::slam::Set<int, int>, axom::slam::policies::STLVectorIndirection<int, axom::spin::OctreeLevel<2, axom::quest::InOutBlockData>*>, axom::slam::policies::StrideOne<int> >::operator[](int)
Frame 4: axom::spin::OctreeBase<2, axom::quest::InOutBlockData>::getOctreeLevel(int)
Frame 5: axom::spin::OctreeBase<2, axom::quest::InOutBlockData>::refineLeaf(axom::spin::OctreeBase<2, axom::quest::InOutBlockData>::BlockIndex const&)
Frame 6: axom::quest::InOutOctree<2>::insertMeshCells()
Frame 7: axom::quest::InOutOctree<2>::generateIndex()
Frame 8: axom::quest::shaping::InOutSampler<2>::initSpatialIndex(double)
Frame 9: axom::quest::SamplingShaper::prepareShapeQuery(axom::klee::Dimensions, axom::klee::Shape const&)
Frame 10: main
Frame 11: __libc_start_main
Frame 12: ../examples/quest_shaping_driver_ex() [0x974f06]
=====

```
![black65](https://user-images.githubusercontent.com/2072964/207137313-4d206d24-7b4d-41ee-9277-174c6046b8f4.png)

**Comment by kennyweiss** [comment] 2022-12-12 19:47
> [ERROR]: Failed Assert: idx >= 0 && idx < SetPosition(m_data.size())
Attempted to access element 31 but map's data has size 31

I think this means that your quadtree only has 32 levels and it's trying to refine past there.
As a quick check, could you please reconfigure Axom with 64 bit indices via `AXOM_USE_64BIT_INDEXTYPE`
https://github.com/LLNL/axom/blob/a1ed65c0c4f9460b1ade310e8cca29395633d0f8/src/cmake/AxomOptions.cmake#L12

Another option is to increase the number of segments per knot span -- via the `-n` parameter in the shaping example: https://github.com/LLNL/axom/blob/a1ed65c0c4f9460b1ade310e8cca29395633d0f8/src/axom/quest/examples/shaping_driver.cpp#L139-L143

Uncommenting the following lines in `InOutOctree` might provide some additional useful information for debugging this
https://github.com/LLNL/axom/blob/a1ed65c0c4f9460b1ade310e8cca29395633d0f8/src/axom/quest/InOutOctree.hpp#L35-L45

**Comment by BradWhitlock** [comment] 2022-12-12 23:22
I recompiled with 64-bit indices. It tries to refine more than before but still bails out. I tried -n values from 1 up to 1000 and that didn't seem to affect things either. I'll try having it write the VTK files for the octree.

```
    67	15:19	../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp
    68	15:19	../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp -n 4
    69	15:19	../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp -n 20
    71	15:19	../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp -n 1
    72	15:19	../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp -n 100
    73	15:20	history
rzgenie10{whitlocb}74: ../examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file black65.yaml --method 0 -v -o 0 -p omp -n 1000
[INFO]: After loading mesh has 30000 elements and (approximate) bounding box { min:(100,25); max:(150,50); range:<50,25> }
[INFO]: ========================Sampling InOut fields for shapes========================
[INFO]: --------------------------- Loading shape 'black65' ----------------------------
[INFO]: Reading file: black65.contour...
[INFO]: Loading contour with 4 pieces
[INFO]: ---------------------------- Generating the octree -----------------------------
[INFO]: Mesh bounding box: { min:(117.003,27); max:(173.191,52.241); range:<56.1885,25.241> }
[INFO]:   Generating InOutOctree over surface mesh with 8008 vertices and 8000 elements.
[INFO]: 	--Inserting vertices took 0.05346206 seconds.
[INFO]: 	--Updating mesh took 0.057164 seconds.
[INFO]:   After inserting vertices, reindexed mesh has 8000 vertices and 8000 cells.
[DEBUG]: Inside InOutOctree::checkValid() to verify state of PR octree
[DEBUG]: --Checking that each vertex is in a leaf block of the tree.
[DEBUG]: done.
[DEBUG]: 	Inserting cells into level 0 took 0.0394056 seconds.
[DEBUG]: 	Inserting cells into level 1 took 0.0401542 seconds.
[DEBUG]: 	Inserting cells into level 2 took 0.0394047 seconds.
[DEBUG]: 	Inserting cells into level 3 took 0.0398387 seconds.
[DEBUG]: 	Inserting cells into level 4 took 0.0387158 seconds.
[DEBUG]: 	Inserting cells into level 5 took 0.0380859 seconds.
[DEBUG]: 	Inserting cells into level 6 took 0.0369785 seconds.
[DEBUG]: 	Inserting cells into level 7 took 0.0366637 seconds.
[DEBUG]: 	Inserting cells into level 8 took 0.0393134 seconds.
[DEBUG]: 	Inserting cells into level 9 took 0.043724 seconds.
[DEBUG]: 	Inserting cells into level 10 took 0.0448544 seconds.
[DEBUG]: 	Inserting cells into level 11 took 0.0398023 seconds.
[DEBUG]: 	Inserting cells into level 12 took 0.0177181 seconds.
[DEBUG]: 	Inserting cells into level 13 took 0.003226 seconds.
[DEBUG]: 	Inserting cells into level 14 took 0.000486459 seconds.
[DEBUG]: 	Inserting cells into level 15 took 0.00010391 seconds.
[DEBUG]: 	Inserting cells into level 16 took 6.1299e-05 seconds.
[DEBUG]: 	Inserting cells into level 17 took 5.6829e-05 seconds.
[DEBUG]: 	Inserting cells into level 18 took 5.2722e-05 seconds.
[DEBUG]: 	Inserting cells into level 19 took 5.2153e-05 seconds.
[DEBUG]: 	Inserting cells into level 20 took 5.2938e-05 seconds.
[DEBUG]: 	Inserting cells into level 21 took 5.2704e-05 seconds.
[DEBUG]: 	Inserting cells into level 22 took 5.2787e-05 seconds.
[DEBUG]: 	Inserting cells into level 23 took 3.8653e-05 seconds.
[DEBUG]: 	Inserting cells into level 24 took 4.8654e-05 seconds.
[DEBUG]: 	Inserting cells into level 25 took 5.2857e-05 seconds.
[DEBUG]: 	Inserting cells into level 26 took 5.1888e-05 seconds.
[DEBUG]: 	Inserting cells into level 27 took 5.1765e-05 seconds.
[DEBUG]: 	Inserting cells into level 28 took 5.5824e-05 seconds.
[DEBUG]: 	Inserting cells into level 29 took 5.4209e-05 seconds.
[DEBUG]: 	Inserting cells into level 30 took 5.2562e-05 seconds.
[DEBUG]: 	Inserting cells into level 31 took 3.8275e-05 seconds.
[DEBUG]: 	Inserting cells into level 32 took 4.3656e-05 seconds.
[DEBUG]: 	Inserting cells into level 33 took 5.6962e-05 seconds.
[DEBUG]: 	Inserting cells into level 34 took 5.569e-05 seconds.
[DEBUG]: 	Inserting cells into level 35 took 5.5038e-05 seconds.
[DEBUG]: 	Inserting cells into level 36 took 5.5929e-05 seconds.
[DEBUG]: 	Inserting cells into level 37 took 5.5161e-05 seconds.
[DEBUG]: 	Inserting cells into level 38 took 4.0897e-05 seconds.
[DEBUG]: 	Inserting cells into level 39 took 3.7671e-05 seconds.
[DEBUG]: 	Inserting cells into level 40 took 5.2504e-05 seconds.
[DEBUG]: 	Inserting cells into level 41 took 6.5135e-05 seconds.
[DEBUG]: 	Inserting cells into level 42 took 5.6834e-05 seconds.
[DEBUG]: 	Inserting cells into level 43 took 5.5251e-05 seconds.
[DEBUG]: 	Inserting cells into level 44 took 5.458e-05 seconds.
[DEBUG]: 	Inserting cells into level 45 took 5.4434e-05 seconds.
[DEBUG]: 	Inserting cells into level 46 took 5.4326e-05 seconds.
[DEBUG]: 	Inserting cells into level 47 took 5.4478e-05 seconds.
[DEBUG]: 	Inserting cells into level 48 took 5.5238e-05 seconds.
[DEBUG]: 	Inserting cells into level 49 took 5.5875e-05 seconds.
[DEBUG]: 	Inserting cells into level 50 took 5.9103e-05 seconds.
[DEBUG]: 	Inserting cells into level 51 took 9.019e-05 seconds.
[DEBUG]: 	Inserting cells into level 52 took 0.000161286 seconds.
[ERROR]: Failed Assert: hasBlock(block)
Block {grid pt: (9380111500756965,11018690529968019); level: 54} was not a block in the tree.
** StackTrace of 9 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: axom::spin::OctreeBase<2, axom::quest::InOutBlockData>::operator[](axom::spin::OctreeBase<2, axom::quest::InOutBlockData>::BlockIndex const&)
Frame 3: axom::quest::InOutOctree<2>::insertMeshCells()
Frame 4: axom::quest::InOutOctree<2>::generateIndex()
Frame 5: axom::quest::shaping::InOutSampler<2>::initSpatialIndex(double)
Frame 6: axom::quest::SamplingShaper::prepareShapeQuery(axom::klee::Dimensions, axom::klee::Shape const&)
Frame 7: main
Frame 8: __libc_start_main
Frame 9: ../examples/quest_shaping_driver_ex() [0x97a866]
=====
```

**Comment by BradWhitlock** [comment] 2022-12-12 23:38
When I plot the octree and surface grids in VisIt, it appears that this spline veers out from where it ought to be, kinking or turning inside out.
![black65_grid](https://user-images.githubusercontent.com/2072964/207182857-80f9f328-b6e5-4601-928b-4b8102e7b6e7.png)

**Comment by BradWhitlock** [comment] 2022-12-13 00:27
In tracing how the contour gets loaded, inside C2CReader::readContour, C2C library call is made to read the contour. Then the code iterates over the pieces in the contour and the piece that is messed up is turned to NURBS by c2c::toNurbs(). This ends up putting a NURBS curve in m_nurbsdata that has 8 control points (the file had 6) and indices 1,2 veer off to the right, causing the kink. The problem is likely in c2c::toNurbs.

**Comment by BradWhitlock** [comment] 2022-12-13 01:25
I made a little program to just call c2c::toNurbs on the curve data:

```
#include <iostream>
#include <vector>
#include "c2c/C2C.hpp"

using std::cout;
using std::endl;


template <typename T>
std::ostream &
operator << (std::ostream &os, const std::vector<T> &v)
{
    os << "[";
    for(size_t i = 0; i < v.size(); i++)
    {
        if(i > 0)
            os << ", ";

        os <<  v[i];
    }
    os << "]";

    return os;
}

int
main(int argc, char *argv[])
{
    c2c::Contour contour = c2c::parseContour("black65.contour");
    auto lengthUnit = c2c::LengthUnit::cm;

    cout << "pieces:" << endl;
    for(auto *piece : contour.getPieces())
    {
        auto obj = c2c::toNurbs(*piece, lengthUnit);
        cout << "  -" << endl;
        cout << "    order: " << obj.order << endl;
        cout << "    knots: " << obj.knots << endl;
        cout << "    weights: " << obj.weights << endl;
        cout << "    controlPoints: " << obj.controlPoints << endl;
    }

    return 0;
}
```

Output
```
pieces:
  -
    order: 2
    knots: [0, 0, 1, 1]
    weights: [1, 1]
    controlPoints: [Point(32cm, 128cm), Point(38cm, 147cm)]
  -
    order: 2
    knots: [0, 0, 1, 1]
    weights: [1, 1]
    controlPoints: [Point(38cm, 147cm), Point(44cm, 146cm)]
  -
    order: 4
    knots: [0, 0, 0, 0, 0.234707, 0.492197, 0.745126, 0.88009, 1, 1, 1, 1]
    weights: [1, 1, 1, 1, 1, 1, 1, 1]
    controlPoints: [Point(44cm, 146cm), Point(48.5244cm, 160.378cm), Point(58.0123cm, 190.53cm), Point(36.0597cm, 129.114cm), Point(35.9747cm, 122.038cm), Point(29.356cm, 115.144cm), Point(27.7538cm, 119.126cm), Point(27cm, 121cm)]
  -
    order: 2
    knots: [0, 0, 1, 1]
    weights: [1, 1]
    controlPoints: [Point(27cm, 121cm), Point(32cm, 128cm)]
```

The "order 4" controlPoints have indices 1,2 (Point(48.5244cm, 160.378cm), Point(58.0123cm, 190.53cm)) that jerk the curve out to the right.

**Comment by mstees** [comment] 2022-12-15 18:14
Hi @BradWhitlock and @kennyweiss,  I wanted to let you know that I am looking into this issue on the C2C side and will keep you posted.

**Comment by kennyweiss** [comment] 2023-01-18 03:37
Note: This problem is due to #979

**Comment by rhornung67** [comment] 2023-03-27 21:14
Fixed in new C2C. Wait for next C2C update, which is imminent.

**Comment by kennyweiss** [comment] 2023-05-20 00:09
I confirmed that `heroic_roses/black65.contour` works as expected with c2c@1.8.0 in #1092 

Here's the verbose output:
```
>./examples/quest_shaping_driver_ex --mesh-file box_2d.root --shape-file ../black65.yaml --method 0 -v -o 0          
[INFO]: After loading mesh has 30000 elements and (approximate) bounding box { min:(100,25); max:(150,50); range:<50,25> }
[INFO]: ========================Sampling InOut fields for shapes========================
[INFO]: --------------------------- Loading shape 'black65' ----------------------------
[INFO]: Reading file: ../data/contours/heroic_roses/black65.contour...
[INFO]: Loading contour with 4 pieces
[INFO]: ---------------------------- Generating the octree -----------------------------
[INFO]: Mesh bounding box: { min:(117,27); max:(147,44); range:<30,17> }
[INFO]:   Generating InOutOctree over surface mesh with 208 vertices and 200 elements.
[INFO]: 	--Inserting vertices took 0.001024867 seconds.
[INFO]: 	--Updating mesh took 0.00104736 seconds.
[INFO]:   After inserting vertices, reindexed mesh has 200 vertices and 200 cells.
[DEBUG]: Inside InOutOctree::checkValid() to verify state of PR octree
[DEBUG]: --Checking that each vertex is in a leaf block of the tree.
[DEBUG]: done.
[DEBUG]: 	Inserting cells into level 0 took 0.000733595 seconds.
[DEBUG]: 	Inserting cells into level 1 took 0.00070705 seconds.
[DEBUG]: 	Inserting cells into level 2 took 0.000741019 seconds.
[DEBUG]: 	Inserting cells into level 3 took 0.000832415 seconds.
[DEBUG]: 	Inserting cells into level 4 took 0.000972374 seconds.
[DEBUG]: 	Inserting cells into level 5 took 0.000959351 seconds.
[DEBUG]: 	Inserting cells into level 6 took 0.000712731 seconds.
[DEBUG]: 	Inserting cells into level 7 took 0.000197013 seconds.
[DEBUG]: 	Inserting cells into level 8 took 3.0074e-05 seconds.
[INFO]: 	--Inserting cells took 0.00628789 seconds.
[DEBUG]: 	Coloring level 8 took 0.000198098 seconds.
[DEBUG]: 	Coloring level 7 took 0.00092091 seconds.
[DEBUG]: 	Coloring level 6 took 0.000819824 seconds.
[DEBUG]: 	Coloring level 5 took 0.000555386 seconds.
[DEBUG]: 	Coloring level 4 took 0.000180905 seconds.
[DEBUG]: 	Coloring level 3 took 7.6016e-05 seconds.
[DEBUG]: 	Coloring level 2 took 1.4458e-05 seconds.
[DEBUG]: 	Coloring level 1 took 2.377e-06 seconds.
[DEBUG]: 	Coloring level 0 took 2.337e-06 seconds.
[INFO]: 	--Coloring octree leaves took 0.00303081 seconds.
[DEBUG]: Inside InOutOctree::checkValid() to verify state of PM octree
[DEBUG]: --Checking that each vertex is in a leaf block of the tree.
[DEBUG]: --Checking that each cell is referenced by the leaf blocks containing its vertices.
[DEBUG]: --Checking that internal blocks have no data, and that leaves satisfy all PM conditions
[DEBUG]: --Checking that all leaves have a color -- black, white and gray
[DEBUG]: --Checking that inside blocks do not neighbor outside blocks
[DEBUG]: done.
[INFO]: 	--Regenerating the mesh took 0.00021413 seconds.
[INFO]:   Finished generating the InOutOctree.
[INFO]: After welding, surface mesh has 200 vertices  and 200 triangles.
[INFO]: -------------------- Querying the octree for shape 'black65'--------------------
[INFO]: 	 Sampling inout field 'inout_black65' took 0.688613304 seconds (@ 1,089,145 queries per second)
[INFO]: --------------Applying replacement rules over for shape 'black65'---------------
[INFO]: ================Generating volume fraction fields for materials=================
[INFO]: Generating volume fraction fields for 'mat_inout_black' material
[INFO]: In computeVolumeFractions(): sample order 9 | sample num qpts 25 |  total samples 750,000
[INFO]: Mesh has dim 2 and 30,000 elements
[INFO]: 	 Generating volume fractions 'vol_frac_black' took 0.183 seconds (@ 164,216 dofs processed per second)
```

Here's a screenshot:
![image](https://github.com/LLNL/axom/assets/5626552/c5480584-92dd-4a82-8bf6-254c70ad311e)

**Closed** 2023-05-20 01:20 UTC
Labels: Spin, Klee
