### ISSUE TITLE
SLIC: Rank count and list formatting

### ISSUE THREAD

**Issue by gberg617** [LLNL/axom#1420] opened 2024-09-23 16:37 UTC
I'm trying to write to a log file using both GenericOutputStream (for messages from the root rank), and LumberjackStream (for messages from another rank that might need to be filtered).  Traditionally, the formatting of this log file would look something like this:

[INFO  ][2024/09/20 18:18:57][     0][     0][0.000000e+00]     Message from root rank
[INFO  ][2024/09/20 18:18:57][     2][     0][2.200000e-02]      Message from rank 2

The number in the third pair of square brackets above indicates the rank that creates the message.  Messages that are filtered typically print only the first rank.

There are two issues I'm encountering trying to format this:

1. GenericOutputStream does not have a rank associated with it.  The formatting of the `<RANK>` keyword will just be empty.  For all of my applications, I prefer the rank to always print "0", and rank count to be "1" so that it has consistent formatting.  Is there a way to override this formatting?  Or would you recommend that I create my own stream class to do this?
2. Lumberjack streams now have the trailing dots "..." for the rank list, even if the rank count is 1.  Is it possible at all to disable the dots so that I just get the first number in the rank list?  This would also help with consistency in formatting.

Any guidance on this would be greatly appreciated!

**Comment by gberg617** [comment] 2024-09-23 16:39
@white238 @bmhan12

**Comment by bmhan12** [comment] 2024-09-23 17:09
> GenericOutputStream does not have a rank associated with it. The formatting of the <RANK> keyword will just be empty. For all of my applications, I prefer the rank to always print "0", and rank count to be "1" so that it has consistent formatting. Is there a way to override this formatting? Or would you recommend that I create my own stream class to do this?

`GenericOutputStream` is for non-MPI use cases and builds without MPI, so there is not a way to get the rank information (the "" parameters):
https://github.com/LLNL/axom/blob/6f5eaa3c2891e6b751adf01ca2d51b8041e98084/src/axom/slic/streams/GenericOutputStream.cpp#L97-L103

You should use `SynchronizedStream` for unfiltered MPI messages. The rank count will always be 1 (no filtering done), and assuming the message is always from root, the rank should be 0:
https://github.com/LLNL/axom/blob/6f5eaa3c2891e6b751adf01ca2d51b8041e98084/src/axom/slic/streams/SynchronizedStream.cpp#L145-L152

--------------------------------------------------------
--------------------------------------------------------

> Lumberjack streams now have the trailing dots "..." for the rank list, even if the rank count is 1. Is it possible at all to disable the dots so that I just get the first number in the rank list? This would also help with consistency in formatting.

I'm not too sure where this is coming from. @white238, could it be this line here in Lumberjack?

https://github.com/LLNL/axom/blob/6f5eaa3c2891e6b751adf01ca2d51b8041e98084/src/axom/lumberjack/Message.cpp#L42-L61

**Comment by bmhan12** [comment] 2024-09-23 18:03
> I had tried the SynchronizedStream previously, the formatting for this worked well. From a conceptual standpoint, I wasn't sure if using this makes sense if it is only used to output messages from a single rank (the root rank). I noticed that the flush method for SynchronizedStream has some MPI logic to check for messages that need to be sent or received. Would these be called when I'm just expecting a single rank to output messages? If so, would there be any performance implications for calling these MPI routines?

I see, that's a good point. You likely would see some costs for those MPI routines.

Alternatively, if you know for sure the `GenericOutputStream` will be used only for the root node, you code use `setFormatString` or a constructor with the `format` parameter  to hardcode the rank/rank count information.

For example, in this Lumberjack format string example:
https://github.com/LLNL/axom/blob/6f5eaa3c2891e6b751adf01ca2d51b8041e98084/src/axom/slic/examples/basic/lumberjack_logging.cpp#L41-L58

You can instead hardcode the rank and rank count:
```
  // Initialize SLIC
  constexpr const char* format = R"(
<MESSAGE>
\t<TIMESTAMP>
\tLEVEL=<LEVEL>
\tRANKS=0
\tRANK_COUNT=1
\tFILE=<FILE>
\tLINE=<LINE>
)";
```

**Comment by gberg617** [comment] 2024-09-23 19:18
This is an interesting point.  The only formatting keyword I generally pass to Slic is `<MESSAGE>` because I find it easier to format the full message in the application code itself.  This also makes it easier to embed certain variables within the message that don't have Slic keywords associated with them such as simulation time and simulation cycle.  As a bit of a side note, this comes at a cost of having to send longer messages when using the Lumberjack stream (since it includes all the formatting), but I don't really know how else to get around this issue.

Perhaps to enforce rank=0, I can check which stream is used when I format my messages and override the `<RANK>` keyword for the string `0`.  This could be a viable alternative.

**Comment by bmhan12** [comment] 2024-10-08 15:41
@gberg617 

@white238 had some suggestions on point 2) with the trailing dots (please correct me if I am misremembering):

- The `ranksLimit` field may be set lower than expected, causing the trailing dots to appear. May make sense to bump it higher: https://github.com/LLNL/axom/blob/e5dcbaa314a6c5d5c76851d24cbef7b87d098840/src/axom/slic/streams/LumberjackStream.hpp#L50-L59
- Potentially using/implementing a version of `SLIC_X_ROOT`/`SLIC_X_IF` macros may be useful in isolating the rank you want printed if the issue is bumping up against the `ranksLimit`: 
  - List of Axom macros: https://axom.readthedocs.io/en/develop/axom/slic/docs/sphinx/sections/appendix.html
  - Axom macros definitions: https://github.com/LLNL/axom/blob/develop/src/axom/slic/interface/slic_macros.hpp

**Comment by bmhan12** [comment] 2024-10-29 20:52
@gberg617 Closing this issue for now. Feel free to re-open this issue/open a new issue if the problem persists!

**Closed by bmhan12** 2024-10-29 20:52 UTC
Labels: Slic, User Request, Reviewed
