### ISSUE TITLE
2 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [LLNL/axom#912] opened 2022-08-21 09:51 UTC
[axom-tests.log](https://github.com/LLNL/axom/files/9388826/axom-tests.log)

**Comment by agcapps** [comment] 2022-08-24 18:37
To excerpt the log file,
- test spio_parallel died in conduit::relay, in hdf5_open_file_for_read(), with message "HDF5 Error code-1 Error opening HDF5 file for read only access: out_spio_parallel_write_read.root"
- test quest_point_in_cell_mfem died.  Here are some messages:

> On curved_3d_refined_4_jittered mesh, verified plausibility in 9191 of 10007 cases (91.8%)
> axom/quest/tests/quest_point_in_cell_mfem.cpp:409: Failure
> The difference between isoparCenter[i] and foundIsoPar[i] is 0.012124988792127039, which exceeds ::EPS, where 
> isoparCenter[i] evaluates to 0,
> foundIsoPar[i] evaluates to 0.012124988792127039, and
> ::EPS evaluates to 1e-08.
> For element 72 coord 0	isoparCenter is(0,0,0)	foundIsoPar is 
> (0.012124988792127039,0.094744793348147407,0.099453759693972632)	
> point in space (-0.13371377649806573,-0.60480007079623654,-0.59057497782467572)

This happens for element 72, 529, 649, 845, 1097, 1098, 1106; foundCellID is -1 where expected to be 1169; and many (10s to 100s) more.

**Comment by agcapps** [comment] 2022-08-24 21:06
I can't reproduce the failure for quest_point_in_cell.  Working on the problem with spio_parallel.

**Comment by agcapps** [comment] 2022-08-24 22:35
Moving from v0.6.1 to develop, the HDF5 problems persist (hdf5_open_file_for_read_write and hdf5_open_file_for_read crash in test spio_parallel and examples sidre_createdatastore_parallel, sidre_generateindex_parallel) but the MFEM crash seems to have been fixed.  This may be because of development and fixes going into quest or the fact that MFEM got updated.

**Comment by cyrush** [comment] 2022-08-24 23:39
@agcapps could this be due to when files are created, an MPI barrier missing?

**Comment by agcapps** [comment] 2022-08-24 23:50
> @agcapps could this be due to when files are created, an MPI barrier missing?

I suppose, but one would think that would show up in all our other testing.

**Comment by agcapps** [comment] 2022-08-24 23:52
I see that the TOSS3 host-config file for rzgenie depends on HDF5 1.8.22, while the port that gets built on FreeBSD is HDF5 1.10.9,1 (I think the ,1 is a FreeBSD patch).  Could that be the problem?

**Comment by cyrush** [comment] 2022-08-24 23:58
We test conduit with newer hdf5 -- I expect it should work.

**Comment by cyrush** [comment] 2022-08-25 00:01
> > @agcapps could this be due to when files are created, an MPI barrier missing?
> 
> I suppose, but one would think that would show up in all our other testing.

race conditions are fun :-)

**Comment by nselliott** [comment] 2022-08-25 00:11
@agcapps Do you know if the files mentioned in the error message exist when those calls are made?  That error could either be that the file isn't found or that it is there but not recognized as a valid HDF5 file.

**Comment by nselliott** [comment] 2022-08-25 00:17
One way to check for race conditions would be to put an MPI Barrier immediately before ever read call in these tests, such as:

`   MPI_Barrier(MPI_COMM_WORLD);`
`   reader.read(ds2->getRoot(), root_name);`

**Comment by agcapps** [comment] 2022-08-25 04:04
@nselliott , I don't know if the files exist or not.  I'll see what happens after adding the calls to `MPI_Barrier()`.  Yes, @cyrush , race conditions are pretty challenging.

**Comment by cyrush** [comment] 2022-08-25 19:55
In case it helps:

```
EXPECT_TRUE(conduit::utils::is_file("my_file.root"))
```

**Comment by agcapps** [comment] 2023-05-10 20:01
Closing: we've done a lot of development in these areas since this issue was opened, and I can't recreate this now with axom develop on freebsd with the pkg mfem-4.4_7.  Axom now requires mfem >= 4.5. See our spack package for mfem: https://github.com/LLNL/axom/blob/878b4d169d20ac46ba214ab528b1b16f593ccb9f/scripts/spack/packages/axom/package.py#L143-L146 (thanks, @kennyweiss !).

@yurivict , please let us know if further test failures come up.  If I can reproduce the failure on my (now working) FreeBSD install, I can help fix problems, and of course, the more details (such as the CMake command line you use) the better chance I have.

**Closed by agcapps** 2023-05-10 20:01 UTC
Labels: Testing, Reviewed
